# このサイト全体のタイトル
site_name: site name

# meta description（og:description・twitter:descriptionでも使用）
description: site description
og_title: og title
og_description: og description
twitter_title: twitter title
twitter_description: |
  twitter description
line_description: line description

# meta keywords
keywords: [keyword1, keyword2, keyword3]

# カノニカル・og:urlなどで使われる、このサイトのURL
# （複数ページあるサイトでは、全てに同じURLを入れないように）
url: http://example.com/

# Facebook OGP・Twitter cardsで使われる画像 フルURLで指定すること
ogp_image_url: http://example.com/ogp.jpg

# Facebookアプリのapp id（入れないとWarningが出る）
facebook_app_id: 99999999999

# Twitter ハッシュタグ
hashtag: hashtag, hashtag2, hashtag3

# Twitter cardsの管理者として登録するアカウント（※任意）
# twitter_card_owner: '@TwitterJP'

# favicon
favicon_url: /favicon.ico

# サイトをホーム画面に追加した際のアイコン画像
# webclipicon_url: http://example.com/webclipicon.png

# iOSにて、サイトをホーム画面に追加した際の、ステータスバーの挙動指定
# ios_status_bar: default
